# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pic',
            field=models.ImageField(upload_to='pic_folder/'),
        ),
    ]
