# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_remove_contact_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='home/shubham/Downloads/download.png', upload_to='pic_folder/'),
        ),
    ]
