# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(upload_to='MEDIA_ROOT', verbose_name='Upload Image'),
        ),
    ]
