# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-01 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20170630_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
