# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-02 14:09
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20170702_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mob_no',
            field=phonenumber_field.modelfields.PhoneNumberField(choices=[('mobile', 'mobile'), ('Home', 'home'), ('Office', 'office'), ('Phone', 'phone')], default='mobile', max_length=128),
        ),
    ]
